//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTful_AngularJs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string MSSV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<int> KHOA { get; set; }
        public string NGANH { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
    }
}
